sonar.projectKey=cagatayuresin_kaclazim
sonar.organization=cagatayuresin

# Project metadata
sonar.projectName=kaclazim
sonar.projectVersion=1.0

# Path to source files
sonar.sources=docs
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**, coverage/**, tests/**